Repository webgme/webgme, pull requests merged in 2018-06, with the labels that each got.

#1609 Show description in PluginConfig dialog and indicate meta-nodes in property-editor.
  src/client/js/Controls/PropertyGrid/Widgets/MetaTypeWidget.js
  src/client/js/Dialogs/PluginConfig/PluginConfigDialog.js
  src/client/js/Dialogs/PluginConfig/styles/PluginConfigDialog.css
  src/client/js/Dialogs/PluginConfig/styles/PluginConfigDialog.scss
  src/client/js/Dialogs/PluginConfig/templates/PluginConfigDialog.html
Labels: Enhancement, Meta, Minor, Plugin, UX/UI

#1610 Fixes #1605 Removing selection of owner, target and pointer in Meta-Editor raises uncaught exception
  src/client/js/Panels/GraphViz/GraphVizPanelControl.js
  src/client/js/Panels/MetaEditor/MetaEditorControl.DiagramDesignerWidgetEventHandlers.js
  src/client/js/Panels/MetaEditor/MetaEditorControl.js
Labels: Bug, Meta, Minor, UX/UI

#1611 Point to webgme-engine 2.19.9 and webgme-user-management-page 0.4.0
  package.json
  src/client/js/Dialogs/PluginResults/PluginResultsDialog.js
Labels: Auth, Enhancement, Major, Server

#1615 Fixes #1612 update node-modules and bower components
  bower.json
  package-lock.json
  package.json
Labels: Enhancement, GME build, Minor

#1613 Allow the webgme server to be mounted at non-root path
  src/client/cssfiles/codemirror/codemirror.bootstrap.css
  src/client/cssfiles/jquery/images/animated-overlay.gif
  src/client/cssfiles/jquery/images/ui-bg_flat_0_aaaaaa_40x100.png
  src/client/cssfiles/jquery/images/ui-bg_flat_75_ffffff_40x100.png
  src/client/cssfiles/jquery/images/ui-bg_glass_55_fbf9ee_1x400.png
  src/client/cssfiles/jquery/images/ui-bg_glass_65_ffffff_1x400.png
  src/client/cssfiles/jquery/images/ui-bg_glass_75_dadada_1x400.png
  src/client/cssfiles/jquery/images/ui-bg_glass_75_e6e6e6_1x400.png
  src/client/cssfiles/jquery/images/ui-bg_glass_95_fef1ec_1x400.png
  src/client/cssfiles/jquery/images/ui-bg_highlight-soft_75_cccccc_1x100.png
  src/client/cssfiles/jquery/images/ui-icons_222222_256x240.png
  src/client/cssfiles/jquery/images/ui-icons_2e83ff_256x240.png
  src/client/cssfiles/jquery/images/ui-icons_454545_256x240.png
  src/client/cssfiles/jquery/images/ui-icons_888888_256x240.png
  src/client/cssfiles/jquery/images/ui-icons_cd0a0a_256x240.png
  src/client/cssfiles/jquery/jquery.dataTables.bootstrapped.css
  src/client/cssfiles/jquery/jquery.layout.css
  src/client/cssfiles/jquery/jquery.layout.webgme.css
  src/client/cssfiles/main.css
  src/client/cssfiles/print.css
  src/client/cssfiles/themes/dawn.css
  src/client/cssfiles/themes/dawn.scss
  src/client/cssfiles/webgme_bootstrap_overrides.css
  src/client/cssfiles/webgme_contextmenu_overrides.css
  src/client/cssfiles/webgme_contextmenu_overrides.scss
  src/client/cssfiles/webgme_fancytree_overrides.css
  src/client/cssfiles/webgme_fancytree_overrides.scss
  src/client/debug.html
  src/client/index.html
  src/client/js/Dialogs/DecoratorSVGExplorer/DecoratorSVGExplorerDialog.js
  src/client/js/Utils/Exporters.js
  src/client/js/Utils/LibraryManager.js
  src/client/js/Utils/SvgManager.js
  src/client/js/Widgets/DiagramDesigner/AutoRouter.Worker.js
  src/client/js/Widgets/UserProfile/UserProfileWidget.js
  src/client/js/start.js
  src/client/main.js
  src/client/mainDEBUG.js
  utils/build/dist/build.js
Labels: Enhancement, Major, Server

#1616 Introduce hidden property in plugin-config option
  src/client/js/Dialogs/PluginConfig/PluginConfigDialog.js
Labels: Enhancement, Minor, Plugin, UX/UI

#1617 Fixes #1614 Ensure sheet is intialized in crosscut before adding new members
  src/client/js/Panels/ControllerBase/DiagramDesignerWidgetMultiTabMemberListControllerBase.js
Labels: Bug, CrossCut, Minor
