Repository webgme/webgme, pull requests merged in 2018-09, with the labels that each got.

#1628 Fixes issue with updates in inheritance tree
  src/client/js/Panels/ObjectBrowser/InheritanceBrowserControl.js
Labels: Bug, Minor, UX/UI

#1630 Fixes #1629 GUIDs and IDs in property editor displayed in monospace font
  src/client/js/Controls/PropertyGrid/Widgets/WidgetBase.js
  src/client/js/Panels/PropertyEditor/PropertyEditorPanelController.js
Labels: Enhancement, Minor, PropertyEditor, UX/UI

#1631 Add link to meta-concepts videos from the MetaEditor
  src/client/js/Panels/MetaEditor/MetaEditorControl.js
Labels: Documentation, Enhancement, Meta, Minor, UX/UI

#1633 Bump user-management-page to v0.4.3
  package.json
Labels: Auth, Enhancement, Minor

#1634 Bump webgme-engine to v2.21.3
  package.json
Labels: Enhancement, Major, Server

#1637 Fixes Microsoft edge issues
  package-lock.json
  src/client/js/Panels/MetaEditor/MetaRelations.js
  src/client/js/Utils/SvgManager.js
  src/client/js/Widgets/DiagramDesigner/DiagramDesignerWidget.js
Labels: Bug, Major, UX/UI

#1638 Remove ES6 language constructs from the generic ui s.t. IE can load
  package.json
  src/client/js/Controls/PropertyGrid/Widgets/SortableWidget.js
  src/client/js/Dialogs/PluginConfig/PluginConfigDialog.js
Labels: Bug, Minor, UX/UI

#1639 Fix Firefox dialog text selection issue.
  src/client/cssfiles/webgme_bootstrap_overrides.css
  src/client/js/Widgets/ProjectRepository/ProjectRepositoryWidget.js
Labels: Bug, Minor, UX/UI

#1640 Allow cancel/close in projects dialog only when there is an open project.
  src/client/js/Dialogs/CreateProject/CreateProjectDialog.js
  src/client/js/Dialogs/CreateProject/styles/CreateProjectDialog.css
  src/client/js/Dialogs/Projects/ProjectsDialog.js
  src/client/js/Dialogs/Projects/styles/ProjectsDialog.css
  src/client/js/Dialogs/Projects/styles/ProjectsDialog.scss
  src/client/js/Dialogs/Projects/templates/ProjectsDialog.html
Labels: Enhancement, Minor, UX/UI
