Repository webgme/webgme, pull requests merged in 2018-03, with the labels that each got.

#1580 Add and expose sortable widget.
  src/client/js/Controls/PropertyGrid/PropertyGridWidgetManager.js
  src/client/js/Controls/PropertyGrid/Widgets/SortableWidget.js
Labels: Enhancement, Minor, UX/UI

#1578 Enable copying and manually editing/pasting blob-hashes in asset widget
  src/client/js/Controls/PropertyGrid/PropertyGridWidgetManager.js
  src/client/js/Controls/PropertyGrid/Widgets/AssetWidget.js
  src/client/js/Controls/PropertyGrid/Widgets/iCheckBoxWidget.js
  src/client/js/Controls/PropertyGrid/Widgets/styles/AssetWidget.css
  src/client/js/Controls/PropertyGrid/Widgets/styles/AssetWidget.scss
  src/client/js/jquery.WebGME.js
Labels: Bug, Enhancement, Minor, UX/UI

#1581 Add description and hidden in schema for Attributes
  package-lock.json
  src/client/decorators/MetaDecorator/DiagramDesigner/AttributeDetailsDialog.js
  src/client/decorators/MetaDecorator/DiagramDesigner/MetaDecorator.DiagramDesignerWidget.js
  src/client/decorators/MetaDecorator/DiagramDesigner/templates/AttributeDetailsDialog.html
  src/client/js/Controls/PropertyGrid/PropertyGridPart.js
  src/client/js/Panels/PropertyEditor/PropertyEditorPanelController.js
Labels: Client library, Enhancement, Minor, UX/UI

#1582 Bump webgme-engine to 2.19.6
  package-lock.json
  package.json
  src/client/js/Controls/PropertyGrid/Widgets/AssetWidget.js
  src/client/js/Panels/PropertyEditor/PropertyEditorPanelController.js
Labels: Enhancement, Major, Server

#1588 Fixes #1584 make sure to clear cookie in browser at logout
  src/client/js/Widgets/UserProfile/UserProfileWidget.js
Labels: Auth, Bug, Minor
