Repository webgme/webgme, pull requests merged in 2018-05, with the labels that each got.

#1597 Fixes #1596 Changes in embedded libraries should not trigger library notification to the user.
  src/client/js/Utils/LibraryManager.js
Labels: Bug, GME Libraries, Minor, UX/UI

#1598 Prevent new active object event when switching to new viz via node registery look-up
  src/client/js/Constants.js
  src/client/js/PanelBase/PanelBase.js
  src/client/js/PanelBase/PanelBaseWithHeader.js
  src/client/js/PanelManager/PanelManager.js
  src/client/js/Panels/Visualizer/VisualizerPanel.js
  src/client/js/Utils/StateManager.js
Labels: Enhancement, Minor, UX/UI

#1602 Release testing fixes
  src/client/js/Utils/LibraryManager.js
Labels: Bug, Client library, Minor, UX/UI

#1604 Make sure video links are present in the tutorial for pdf generation
  docs/analysis_tools/creating_the_simulator_plugin.rst
  docs/deployment/authentication.rst
  docs/deployment/secure_deployment.rst
  docs/deployment/third_part_integration.rst
  docs/getting_started/creating_a_repository.rst
  docs/getting_started/dependencies.rst
  docs/index.rst
  docs/interpreters/creating_the_interpreter.rst
  docs/meta_modeling/creating_our_first_project.rst
  docs/meta_modeling/creating_the_meta_model.rst
  docs/meta_modeling/meta_modeling_concepts.rst
  docs/meta_modeling/modeling_in_webgme.rst
  docs/visualization/generic_visualization.rst
Labels: Documentation, Enhancement, Minor

#1608 Adds a RangeWidget for numerical values with defined increment.
  package.json
  src/client/js/Controls/PropertyGrid/PropertyGridWidgetManager.js
  src/client/js/Controls/PropertyGrid/PropertyGridWidgets.js
  src/client/js/Controls/PropertyGrid/Widgets/RangeWidget.js
  src/client/js/Dialogs/PluginConfig/PluginConfigDialog.js
Labels: Enhancement, Minor, UX/UI
