Repository webgme/webgme, pull requests merged in 2019-04, with the labels that each got.

#1676 Fixes copy paste from key board inside root node
  src/client/js/Panels/ModelEditor/ModelEditorControl.DiagramDesignerWidgetEventHandlers.js
Labels: Bug, Minor, ModelEditor

#1679 Navigation title
  config/componentsGenericUIDefaults.json
  package-lock.json
  src/client/js/Dialogs/Projects/styles/ProjectsDialog.css
  src/client/js/PanelBase/PanelBaseWithHeader.js
  src/client/js/PanelBase/styles/PanelBaseWithHeader.css
  src/client/js/PanelBase/styles/PanelBaseWithHeader.scss
  src/client/js/Panels/ModelEditor/ModelEditorControl.js
  src/client/js/Panels/ModelEditor/ModelEditorPanel.js
Labels: Enhancement, Major, UX/UI

#1681 Hiding header breadcrumb of the node navigation
  config/componentsGenericUIDefaults.json
  src/client/js/Panels/Header/ProjectNavigatorController.js
Labels: Enhancement, Minor, UX/UI
