Repository webgme/webgme, pull requests merged in 2023-09, with the labels that each got.

#1775 Add missing typescript fn declaration for the Client
  typings/webgme.d.ts
Labels: Enhancement, Minor, Client library, TypeScript

#1776 webgme-engine v2.26.0 and node_modules bump
  config/components.default.js
  package-lock.json
  package.json
Labels: Enhancement, Major, dependencies

#1780 Bump user-management-page to v0.6.0
  package.json
Labels: Enhancement, Minor, UX/UI, Auth
